/**
 * Sync avatar fallback position_catalog.py from Evaalo Job Catalog.
 * One row per roleKey (prefers mid career level). Excludes ambiguous legacy titles.
 * Usage: npx tsx src/scripts/sync-position-catalog.ts
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { JOB_CATALOG } from '../shared/jobCatalog/buildCatalog.js';
import { AMBIGUOUS_LEGACY_TITLES } from '../shared/jobCatalog/legacyAliases.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const DOMAIN_TO_INDUSTRY: Record<string, string> = {
    engineering: 'engineering',
    oil_gas: 'engineering',
    technology: 'technology',
    finance: 'business',
    hr: 'business',
    sales: 'business',
    marketing: 'business',
    admin: 'leadership_admin',
    procurement: 'business',
    product_design: 'creative',
    project: 'business',
    hse_security: 'engineering',
    legal: 'legal_services',
    hospitality: 'hospitality_services',
    healthcare: 'healthcare',
};

const BLOCKED_TITLES = new Set([
    ...AMBIGUOUS_LEGACY_TITLES.map((t) => t.toLowerCase()),
    'accountant',
    'procurement office',
    'fire fighting engineer',
    'intern / trainee',
]);

function pickCatalogRows() {
    const byRoleKey = new Map<string, (typeof JOB_CATALOG)[number]>();
    for (const entry of JOB_CATALOG) {
        const existing = byRoleKey.get(entry.roleKey);
        if (!existing || entry.careerLevel === 'mid') {
            byRoleKey.set(entry.roleKey, entry);
        }
    }
    return [...byRoleKey.values()]
        .filter((e) => !BLOCKED_TITLES.has(e.displayTitle.toLowerCase()))
        .sort((a, b) => a.displayTitle.localeCompare(b.displayTitle));
}

function buildPython(rows: ReturnType<typeof pickCatalogRows>): string {
    const lines = rows.map((r) => {
        const category = r.specialization.replace(/[^a-z0-9]+/gi, '_').toLowerCase().slice(0, 40)
            || r.roleKey;
        const industry = DOMAIN_TO_INDUSTRY[r.domain] || 'business';
        const title = r.displayTitle.replace(/"/g, '\\"');
        return `    ("${title}", "${category}", "${industry}"),`;
    });

    return `"""Canonical Evaalo position titles -> slug, category, industry_family.

AUTO-GENERATED by sync-position-catalog.ts from apps/shared/jobCatalog.
Do not edit manually — re-run: npx tsx src/scripts/sync-position-catalog.ts
"""

from __future__ import annotations

# (title, category, industry_family)
POSITION_ROWS: list[tuple[str, str, str]] = [
${lines.join('\n')}
]
`;
}

function main(): void {
    const rows = pickCatalogRows();
    const outPath = path.resolve(
        __dirname,
        '../../../avatar-evaalov2/src/voice_interview/data/question_bank_sources/position_catalog.py'
    );
    fs.writeFileSync(outPath, buildPython(rows), 'utf8');
    console.log(`✅ sync-position-catalog: wrote ${rows.length} rows → ${outPath}`);
}

main();
