"""Wave 2 QA scorecard — 9 L3 packs via scenario factory."""

from __future__ import annotations

from qa_l3_scenario_factory import PackScenarioConfig

WAVE_2_CONFIGS: dict[str, PackScenarioConfig] = {
    "frontend_developer": PackScenarioConfig(
        prefix="fe",
        academic_text="كل شي تعلمته بالجامعة عن React و TypeScript ومشروع واجهات بدون إنتاج",
        expert_text="اشتغلت خمس سنوات ميزات React بالإنتاج وحسّنت performance و Core Web Vitals",
        career_switch_text="غيرت مجالي من مجال آخر لتطوير واجهات قبل سنتين",
        entry_text="انا خريج حديث وأول وظيفة frontend اشتغلتها تحت إشراف مطور أول",
        trainee_text="فترة تدريب frontend تعلمت فيها TypeScript و component architecture مع فريق",
        domain_rich_text="حسّنا bundle size و lazy loading بعد قياس LCP و accessibility fixes",
        stt_expert_text="اشتغلت. React. TypeScript. performance. واجهة.",
    ),
    "devops_engineer": PackScenarioConfig(
        prefix="dops",
        academic_text="مشروع CI/CD أكاديمي بالجامعة عن Docker بدون on-call حقيقي",
        expert_text="اشتغلت سنوات على pipeline و Kubernetes و Terraform وحليت incident إنتاج",
        career_switch_text="غيرت مجالي من تطوير لديفوبس قبل سنتين",
        entry_text="انا خريج حديث وأول وظيفة DevOps تحت إشراف مهندس منصات",
        trainee_text="فترة تدريب ديفوبس تعلمت فيها Docker و CI/CD basics مع الفريق",
        domain_rich_text="أصلحنا incident بعد alert من Prometheus وعملنا postmortem و GitOps fix",
        stt_expert_text="اشتغلت. pipeline. Kubernetes. Terraform. incident.",
    ),
    "data_analyst": PackScenarioConfig(
        prefix="da",
        academic_text="مشروع تحليل بيانات بالجامعة بSQL و Excel فقط بدون قرار إداري",
        expert_text="اشتغلت سنوات تحليل SQL و Power BI وأثر على قرار KPI للإدارة",
        career_switch_text="غيرت مجالي من مجال آخر لتحليل البيانات قبل سنتين",
        entry_text="انا خريج حديث وأول تقرير بيانات سلّمته للإدارة تحت إشراف",
        trainee_text="فترة تدريب محلل بيانات تعلمت SQL و dashboard basics مع الفريق",
        domain_rich_text="اكتشفنا anomaly بالبيانات بعد validation وغيّرنا توصية funnel KPI",
        stt_expert_text="اشتغلت. SQL. KPI. dashboard. تحليل.",
    ),
    "qa_engineer": PackScenarioConfig(
        prefix="qa",
        academic_text="مشروع اختبار برمجيات بالجامعة بدون release حقيقي",
        expert_text="اشتغلت سنوات regression suite و automation واكتشفت bug حرج قبل release",
        career_switch_text="غيرت مجالي من تطوير لضمان جودة البرمجيات قبل سنتين",
        entry_text="انا خريج حديث وأول مهمة QA اشتغلتها على release تحت إشراف",
        trainee_text="فترة تدريب QA تعلمت test cases و bug reporting مع مهندس جودة",
        domain_rich_text="وثّقت bug بrepro steps و severity وتابعته للإغلاق قبل الإطلاق",
        stt_expert_text="اشتغلت. regression. automation. bug. release.",
    ),
    "customer_support": PackScenarioConfig(
        prefix="cs",
        academic_text="تدريب خدمة عملاء بالجامعة على نظريات CX بدون queue ضاغط",
        expert_text="اشتغلت سنوات tickets و escalation وحققت CSAT بعد شكوى صعبة",
        career_switch_text="غيرت مجالي من مبيعات لدعم العملاء قبل سنة",
        entry_text="انا خريج حديث وأول وظيفة دعم عملاء على queue تحت إشراف",
        trainee_text="فترة تدريب helpdesk تعلمت Zendesk و SLA basics مع المشرف",
        domain_rich_text="هديت عميل غاضب ووثّقت التذكرة وصعدت بالوقت المناسب",
        stt_expert_text="اشتغلت. ticket. CSAT. escalation. عميل.",
    ),
    "operations_coordinator": PackScenarioConfig(
        prefix="ops",
        academic_text="مشروع تنسيق عمليات بالجامعة بدون vendor حقيقي",
        expert_text="اشتغلت سنوات حسّنت SOP و vendor SLA وقلّلنا bottleneck بالعمليات",
        career_switch_text="غيرت مجالي من إدارة مشاريع لتنسيق العمليات قبل سنتين",
        entry_text="انا خريج حديث وأول مهمة تنسيق عمليات تحت إشراف منسق أول",
        trainee_text="فترة تدريب عمليات تعلمت KPI reporting مع فريق التشغيل",
        domain_rich_text="أصلحنا bottleneck بتنسيق cross-functional ورفعنا KPI throughput",
        stt_expert_text="حسّنت. SOP. vendor. KPI. عمليات.",
    ),
    "accounts_payable": PackScenarioConfig(
        prefix="ap",
        academic_text="تدريب محاسبة بالجامعة على نظريات AP بدون payment run حقيقي",
        expert_text="اشتغلت سنوات three-way match و vendor reconciliation ومنعت duplicate payment",
        career_switch_text="غيرت مجالي من محاسبة عامة لذمم دائنة قبل سنة",
        entry_text="انا خريج حديث وأول مهمة AP على فواتير تحت إشراف محاسب",
        trainee_text="فترة تدريب AP تعلمت invoice processing basics مع الفريق",
        domain_rich_text="اكتشفت عدم مطابقة PO و GRN قبل payment run وسويت reconciliation",
        stt_expert_text="اشتغلت. invoice. three-way. vendor. payment.",
    ),
    "financial_analyst": PackScenarioConfig(
        prefix="fa",
        academic_text="مشروع نموذج مالي أكاديمي بالجامعة بدون تقرير إدارة حقيقي",
        expert_text="اشتغلت سنوات FP&A variance analysis و rolling forecast وأثرت على قرار",
        career_switch_text="غيرت مجالي من محاسبة لتحليل مالي قبل سنتين ونقلت مهارات التقارير",
        entry_text="انا خريج حديث وأول تقرير variance سلّمته للإدارة تحت إشراف",
        trainee_text="فترة تدريب تحليل مالي تعلمت Excel model basics مع المحلل",
        domain_rich_text="شرحنا variance P&L بdrivers و sensitivity وغيّرنا التوقع",
        stt_expert_text="اشتغلت. variance. forecast. FP&A. model.",
    ),
    "internal_auditor": PackScenarioConfig(
        prefix="ia",
        academic_text="مشروع تدقيق أكاديمي بالجامعة بدون engagement ميداني",
        expert_text="اشتغلت سنوات control testing و raising finding وتابعت remediation",
        career_switch_text="غيرت مجالي من محاسبة للتدقيق الداخلي قبل سنتين",
        entry_text="انا خريج حديث وأول مهمة تدقيق ضوابط تحت إشراف مدقق",
        trainee_text="فترة تدريب تدقيق تعلمت sampling و workpapers مع الفريق",
        domain_rich_text="اختبرنا ضابط SOX ورفعنا finding بevidence واضح وتابعنا الإغلاق",
        stt_expert_text="اشتغلت. control. finding. sampling. تدقيق.",
    ),
}
