// Wave 1B L3 packs — Reservoir, Drilling, Civil, Site, Process Engineering
// ============================================

import type { DomainPack, ExperienceTrackKey, InterviewPath } from './domainPacks.js';
import {
    ACADEMIC_TRACKS,
    FIELD_TRACKS,
    WAVE_3_ENRICHED_VERSION,
    enrichedPath,
} from './wave3EnrichedHelpers.js';
import { rubricFor } from './packRubrics.js';

/** @deprecated use WAVE_3_ENRICHED_VERSION for Wave 3 enriched packs */
export const WAVE_1B_PACK_VERSION = WAVE_3_ENRICHED_VERSION;

export const RESERVOIR_ENGINEER: DomainPack = {
    packKey: 'reservoir_engineer',
    packVersion: WAVE_1B_PACK_VERSION,
    roleKey: 'reservoir_engineer',
    domain: 'engineering',
    specialization: 'Reservoir Engineering',
    roleAliases: [
        'reservoir engineer', 'reservoir engineering', 'reservoir eng',
        'مهندس مكامن', 'هندسة مكامن', 'مهندس مخازن نفطية',
    ],
    excludeKeywords: [
        'drilling engineer', 'drilling rig', 'mud engineer', 'civil engineer',
        'survey engineer', 'recruiter', 'process engineer manufacturing',
        'lean manufacturing', 'assembly line',
    ],
    matchKeywords: [
        'reservoir', 'simulation', 'history matching', 'material balance', 'pvt',
        'decline curve', 'recovery factor', 'petrophysics', 'eclipse', 'cmg', 'petrel',
        'مكمن', 'محاكاة', 'احتياطي', 'استخلاص',
    ],
    terminology: [
        'reservoir simulation', 'history matching', 'material balance', 'PVT',
        'decline curve analysis', 'recovery factor', 'OOIP', 'OGIP', 'CMG', 'Eclipse',
        'Petrel', 'permeability', 'porosity', 'saturation', 'bottomhole pressure',
        'productivity index', 'well test analysis',
    ],
    domainGuidance: [
        'Domain: Reservoir Engineering — subsurface characterization, simulation, reserves, recovery.',
        'Academic candidates: graduation projects, simulation inputs/assumptions, theoretical cases.',
        'Field-experienced: real well/field data, pressure/production trends, model validation.',
        'Probe history matching, uncertainty, and how forecasts changed decisions.',
        'Weak answers: tool names only, no data, no validation of assumptions.',
    ].join(' '),
    competencies: [
        {
            competencyKey: 'reservoir_characterization',
            title: 'Reservoir Characterization',
            priority: 'critical',
            questionObjective: 'قياس فهم بناء نموذج المكمن من بيانات جيولوجية وبتروفيزيائية.',
            expectedEvidence: ['porosity/permeability', 'PVT', 'تقسيم طبقات', 'ربط بالإنتاج'],
            redFlags: ['لا بيانات', 'خلط جيولوجيا بإنتاج بلا ربط'],
            scoreRubric: rubricFor('reservoir_characterization'),
            followUpRules: ['اسأل شنو البيانات اللي اعتمدت عليها فعلاً.'],
        },
        {
            competencyKey: 'simulation_and_forecast',
            title: 'Simulation & Forecasting',
            priority: 'critical',
            questionObjective: 'قياس بناء وتشغيل نموذج محاكاة وتوقعات الإنتاج.',
            expectedEvidence: ['CMG/Eclipse/Petrel', 'مدخلات', 'history matching', 'سيناريوهات'],
            redFlags: ['محاكاة بلا تحقق', 'لا سيناريوهات'],
            scoreRubric: rubricFor('simulation_and_forecast'),
            followUpRules: ['اسأل عن الافتراضات الحساسة وكيف اختبرتها.'],
        },
        {
            competencyKey: 'production_analysis',
            title: 'Production Performance Analysis',
            priority: 'high',
            questionObjective: 'قياس تحليل أداء الإنتاج والضغط والاتجاهات.',
            expectedEvidence: ['decline curve', 'ضغط', 'Water Cut', 'GOR', 'مقارنة بالتنبؤ'],
            redFlags: ['لا اتجاهات', 'قرار بلا بيانات'],
            scoreRubric: rubricFor('production_analysis'),
            followUpRules: ['اطلب مؤشر قبل/بعد التحليل.'],
        },
        {
            competencyKey: 'reserves_and_recovery',
            title: 'Reserves & Recovery Strategy',
            priority: 'high',
            questionObjective: 'قياس تقدير الاحتياطي وفرص تحسين الاستخلاص.',
            expectedEvidence: ['OOIP/OGIP', 'recovery factor', 'خطة تطوير', 'اقتصاديات'],
            redFlags: ['أرقام بلا منهجية', 'لا خطة تطوير'],
            scoreRubric: rubricFor('reserves_and_recovery'),
            followUpRules: ['اسأل كيف غيّر التوصية قرار الإدارة.'],
        },
        {
            competencyKey: 'uncertainty_management',
            title: 'Uncertainty & Model Risk',
            priority: 'high',
            questionObjective: 'قياس التعامل مع عدم اليقين في البيانات والنماذج.',
            expectedEvidence: ['حساسية', 'سيناريوهات', 'تواصل المخاطر'],
            redFlags: ['يقين زائف', 'يتجاهل الفجوات'],
            scoreRubric: rubricFor('uncertainty_management'),
            followUpRules: ['اسأل عن أكبر مصدر عدم يقين وكيف عالجته.'],
        },
        {
            competencyKey: 'technical_communication',
            title: 'Technical Communication',
            priority: 'medium',
            questionObjective: 'قياس شرح النتائج التقنية لغير المتخصصين.',
            expectedEvidence: ['تقارير', 'رسوم', 'توصيات واضحة'],
            redFlags: ['تعقيد بلا رسالة'],
            scoreRubric: rubricFor('technical_communication'),
            followUpRules: ['اسأل كيف قنعت العمليات بتوصية.'],
        },
    ],
    suggestedAnchorQuestions: [
        'اذكرلي دراسة مكمن أو نموذج محاكاة اشتغلت عليه — شنو كان الهدف وشنو النتيجة؟',
        'شلون تقيّم أداء المكمن من بيانات الضغط والإنتاج — شنو المؤشرات الأساسية؟',
        'اذكرلي موقف ظهر فيه اختلاف كبير بين التنبؤ والإنتاج الفعلي — شنو سويت؟',
    ],
    supportedExperienceTracks: [
        {
            trackKey: 'academic_only',
            detectSignals: ['جامعة', 'تخرج', 'محاكاة', 'مشروع تخرج', 'thesis', 'cmg', 'eclipse'],
            acceptableEvidence: ['مشروع تخرج', 'محاكاة', 'بيانات أكاديمية'],
            questionDifficulty: 1,
            openingAnchors: [
                'اذكرلي مشروع تخرج أو محاكاة مكمن — شنو المدخلات وشنو النتيجة؟',
                'شنو أصعب افتراض بالنموذج وكيف تحققت منه نظرياً؟',
            ],
            followUpHints: ['لا تفترض خبرة حقل'],
            rubricAdjustments: 'اقبل أدلة أكاديمية ومحاكاة.',
        },
        {
            trackKey: 'trainee',
            detectSignals: ['تدريب', 'متدرب', 'internship', 'co-op'],
            acceptableEvidence: ['مهام محددة', 'إشراف', 'ملاحظات'],
            questionDifficulty: 1,
            openingAnchors: ['شنو تعلمت عن تحليل المكمن بفترة التدريب؟'],
            followUpHints: ['اسأل عن الإشراف والأدوات'],
        },
        {
            trackKey: 'entry_level',
            detectSignals: ['خريج', 'حديث تخرج', 'أول وظيفة'],
            acceptableEvidence: ['أول مهمة', 'تعلم سريع'],
            questionDifficulty: 1,
            openingAnchors: ['اذكرلي أول تحليل مكمن بعد التخرج — شنو سويت؟'],
            followUpHints: ['اطلب خطوات محددة'],
        },
        {
            trackKey: 'experienced',
            detectSignals: ['حقل', 'مكمن', 'history matching', 'decline', 'اشتغلت', 'field'],
            acceptableEvidence: ['بيانات حقيقية', 'نموذج مُحقق', 'توصية'],
            questionDifficulty: 3,
            openingAnchors: [
                'اذكرلي حقل أو مكمن اشتغلت عليه — شنو التحدي وشنو البيانات؟',
                'شلون عملت history matching لحالة حقيقية؟',
            ],
            followUpHints: ['اطلب أرقام ومؤشرات'],
        },
        {
            trackKey: 'senior',
            detectSignals: ['senior', 'lead', 'manager', 'استراتيجية', 'احتياطي'],
            acceptableEvidence: ['قرار تطوير', 'فريق', 'تأثير على الحقل'],
            questionDifficulty: 3,
            openingAnchors: ['اذكرلي توصية تطوير مكمن مهم — شنو التأثير؟'],
            followUpHints: ['اسأل عن trade-offs'],
        },
        {
            trackKey: 'career_switcher',
            detectSignals: ['غيرت مجال', 'انتقلت', 'career change', 'من مجال'],
            acceptableEvidence: ['تعلم سريع', 'مهارات منقولة'],
            questionDifficulty: 2,
            openingAnchors: ['ليش انتقلت لهندسة المكامن وشنو نقلته من مجالك السابق؟'],
            followUpHints: ['اربط بمثال تعلم'],
        },
    ],
    interviewPaths: [
        {
            pathKey: 'reservoir_experienced',
            steps: [
                { stepKey: 'mode', topicLabel: 'Mode', sampleQuestion: 'خبرتك أكثر محاكاة ولا تحليل إنتاج ميداني؟' },
                { stepKey: 'asset', competencyKey: 'reservoir_characterization', topicLabel: 'Asset', sampleQuestion: 'اذكرلي مكمن أو حقل — شنو خصائصه الأساسية؟' },
                { stepKey: 'data', competencyKey: 'production_analysis', topicLabel: 'Data', sampleQuestion: 'شنو البيانات اللي راجعتها قبل بناء النموذج؟' },
                { stepKey: 'model', competencyKey: 'simulation_and_forecast', topicLabel: 'Model', sampleQuestion: 'شلون بنيت أو حدّثت النموذج؟' },
                { stepKey: 'match', competencyKey: 'simulation_and_forecast', topicLabel: 'History match', sampleQuestion: 'شلون طابقت النموذج مع الإنتاج الفعلي؟' },
                { stepKey: 'forecast', competencyKey: 'reserves_and_recovery', topicLabel: 'Forecast', sampleQuestion: 'شنو التوقع أو التوصية اللي طلعت؟' },
                { stepKey: 'result', topicLabel: 'Result', sampleQuestion: 'شنو القرار أو النتيجة بعد التحليل؟' },
            ],
        },
        {
            pathKey: 'reservoir_academic',
            steps: [
                { stepKey: 'project', competencyKey: 'simulation_and_forecast', topicLabel: 'Project', sampleQuestion: 'اذكرلي مشروع تخرج أو محاكاة — شنو الهدف؟' },
                { stepKey: 'characterize', competencyKey: 'reservoir_characterization', topicLabel: 'Characterize', sampleQuestion: 'شنو خصائص المكمن أو البيانات اللي استخدمتها؟' },
                { stepKey: 'inputs', topicLabel: 'Inputs', sampleQuestion: 'شنو المدخلات والافتراضات؟' },
                { stepKey: 'model', competencyKey: 'simulation_and_forecast', topicLabel: 'Model', sampleQuestion: 'شلون بنيت أو شغّلت النموذج؟' },
                { stepKey: 'validation', competencyKey: 'uncertainty_management', topicLabel: 'Validation', sampleQuestion: 'شلون تحققت من منطقية النتائج؟' },
                { stepKey: 'learning', topicLabel: 'Learning', sampleQuestion: 'شنو أهم تعلم من المشروع؟' },
            ],
        },
    ],
};

export const DRILLING_ENGINEER: DomainPack = {
    packKey: 'drilling_engineer',
    packVersion: WAVE_1B_PACK_VERSION,
    roleKey: 'drilling_engineer',
    domain: 'engineering',
    specialization: 'Drilling Engineering',
    roleAliases: [
        'drilling engineer', 'drilling engineering', 'drill engineer',
        'مهندس حفر', 'هندسة حفر', 'مهندس آبار',
    ],
    excludeKeywords: [
        'reservoir engineer', 'reservoir simulation', 'civil engineer', 'survey engineer',
        'recruiter', 'manufacturing process', 'lean manufacturing',
    ],
    matchKeywords: [
        'drilling', 'well control', 'mud', 'casing', 'bha', 'rop', 'npt',
        'directional drilling', 'kick', 'blowout', 'rig', 'bit', 'حفر', 'بئر', 'وحدة حفر',
    ],
    terminology: [
        'well control', 'mud weight', 'casing design', 'BHA', 'ROP', 'NPT',
        'directional drilling', 'kick detection', 'choke manifold', 'cementing',
        'pore pressure', 'fracture gradient', 'trip sheet', 'drilling program',
        'MWD/LWD', 'derrick', 'blowout preventer', 'HSE', 'permit to work',
    ],
    domainGuidance: [
        'Domain: Drilling Engineering — well planning, operations, well control, NPT reduction.',
        'Probe real rig/downhole decisions: mud weight, casing points, well control response.',
        'Academic/trainee: drilling projects, simulations, internship observations — not assumed rig authority.',
        'Safety and well control are non-negotiable — weak answers skip procedures.',
    ].join(' '),
    competencies: [
        {
            competencyKey: 'drilling_program_design',
            title: 'Drilling Program Design',
            priority: 'critical',
            questionObjective: 'قياس تخطيط برنامج الحفر (تسلسل، أحجام أقطار، تعليق).',
            expectedEvidence: ['casing points', 'mud plan', 'BHA', 'أهداف الحفر'],
            redFlags: ['خطة عامة', 'لا تبرير تقني'],
            scoreRubric: rubricFor('drilling_program_design'),
            followUpRules: ['اسأل لماذا اخترت نقطة تعليق معينة.'],
        },
        {
            competencyKey: 'well_control',
            title: 'Well Control & Pressure Management',
            priority: 'critical',
            questionObjective: 'قياس فهم ضغط البئر والسيطرة على الركود.',
            expectedEvidence: ['kick', 'mud weight', 'choke', 'إجراءات'],
            redFlags: ['يتجاهل well control', 'لا إجراءات'],
            scoreRubric: rubricFor('well_control'),
            followUpRules: ['اسأل عن خطوات فعلية عند مؤشر kick.'],
        },
        {
            competencyKey: 'drilling_operations',
            title: 'Drilling Operations & Parameters',
            priority: 'high',
            questionObjective: 'قياس متابعة معاملات الحفر وتحسين الأداء.',
            expectedEvidence: ['ROP', 'WOB', 'RPM', 'مشاكل downhole'],
            redFlags: ['لا معاملات', 'لا تشخيص'],
            scoreRubric: rubricFor('drilling_operations'),
            followUpRules: ['اطلب مثال NPT وكيف قلّلته.'],
        },
        {
            competencyKey: 'mud_and_fluids',
            title: 'Drilling Fluids & Hydraulics',
            priority: 'high',
            questionObjective: 'قياس اختيار وإدارة طين الحفر والهيدروليك.',
            expectedEvidence: ['mud weight', 'rheology', 'losses', 'تعديل'],
            redFlags: ['لا فهم للطين', 'خلط مع إنتاج'],
            scoreRubric: rubricFor('mud_and_fluids'),
            followUpRules: ['اسأل متى غيّرت وزن الطين ولماذا.'],
        },
        {
            competencyKey: 'hse_rig_safety',
            title: 'HSE & Rig Safety',
            priority: 'high',
            questionObjective: 'قياس السلامة على الحفرية والتصاريح.',
            expectedEvidence: ['PTW', 'JSA', 'BOP tests', 'تصعيد'],
            redFlags: ['تجاهل HSE'],
            scoreRubric: rubricFor('hse_rig_safety'),
            followUpRules: ['اسأل عن موقف سلامة حرج.'],
        },
        {
            competencyKey: 'coordination_communication',
            title: 'Rig Coordination & Communication',
            priority: 'medium',
            questionObjective: 'قياس التنسيق مع شركة الحفر والخدمات والعمليات.',
            expectedEvidence: ['تقارير يومية', 'NPT meeting', 'قرارات سريعة'],
            redFlags: ['لا تنسيق', 'تواصل ضعيف'],
            scoreRubric: rubricFor('coordination_communication'),
            followUpRules: ['اسأل كيف حلّيت خلاف تقني تحت ضغط الوقت.'],
        },
    ],
    suggestedAnchorQuestions: [
        'اذكرلي بئر أو عملية حفر شاركت بيها — شنو كان دورك وشنو التحدي الأصعب؟',
        'شلون تتعامل مع ضغط البئر أو سيطرة البئر أثناء الحفر — شنو الإجراءات اللي تتأكد منها؟',
        'اذكرلي حالة تغيّر فيها مخطط الحفر بسبب ظروف downhole — شنو القرار اللي اتخذته؟',
    ],
    supportedExperienceTracks: [
        {
            trackKey: 'academic_only',
            detectSignals: ['جامعة', 'تخرج', 'مشروع تخرج', 'نظري', 'thesis'],
            acceptableEvidence: ['تصميم برنامج حفر نظري', 'مشروع أكاديمي'],
            questionDifficulty: 1,
            openingAnchors: ['اذكرلي مشروع حفر أكاديمي — شنو صممت أو حللت؟'],
            followUpHints: ['لا تفترض خبرة rig'],
        },
        {
            trackKey: 'trainee',
            detectSignals: ['تدريب', 'متدرب', 'internship', 'rig visit'],
            acceptableEvidence: ['ملاحظات rig', 'مهام بإشراف'],
            questionDifficulty: 1,
            openingAnchors: ['شنو شفت على الحفرية وأنت متدرب؟'],
            followUpHints: ['اسأل عن well control basics'],
        },
        {
            trackKey: 'entry_level',
            detectSignals: ['خريج', 'حديث تخرج', 'أول وظيفة'],
            acceptableEvidence: ['أول بئر', 'تعلم'],
            questionDifficulty: 1,
            openingAnchors: ['اذكرلي أول مهمة حفر بعد التخرج — شنو تعلمت؟'],
            followUpHints: ['خطوات محددة'],
        },
        {
            trackKey: 'experienced',
            detectSignals: ['rig', 'حفرية', 'npt', 'kick', 'bha', 'اشتغلت', 'field'],
            acceptableEvidence: ['قرار حفر', 'well control', 'نتيجة'],
            questionDifficulty: 3,
            openingAnchors: [
                'اذكرلي حالة NPT أو مشكلة downhole — شنو التشخيص والحل؟',
                'شلون قررت تعديل وزن الطين أو البرنامج ميدانياً؟',
            ],
            followUpHints: ['اطلب معاملات وأرقام'],
        },
        {
            trackKey: 'senior',
            detectSignals: ['senior', 'supervisor', 'manager', 'lead', 'برنامج حفر'],
            acceptableEvidence: ['قيادة', 'تحسين تكلفة/وقت', 'HSE'],
            questionDifficulty: 3,
            openingAnchors: ['اذكرلي برنامج حفر قدته — شنو أكبر تحدي ونتيجته؟'],
            followUpHints: ['trade-offs'],
        },
        {
            trackKey: 'career_switcher',
            detectSignals: ['غيرت مجال', 'انتقلت', 'career change'],
            acceptableEvidence: ['تعلم حفر', 'مهارات منقولة'],
            questionDifficulty: 2,
            openingAnchors: ['ليش انتقلت لهندسة الحفر وشنو نقلته؟'],
            followUpHints: ['مثال تعلم سريع'],
        },
    ],
    interviewPaths: [
        {
            pathKey: 'drilling_operations',
            steps: [
                { stepKey: 'well', topicLabel: 'Well', sampleQuestion: 'اذكرلي بئر — شنو نوع الحفر والبيئة؟' },
                { stepKey: 'plan', competencyKey: 'drilling_program_design', topicLabel: 'Plan', sampleQuestion: 'شنو أهم قرار بالبرنامج قبل البدء؟' },
                { stepKey: 'mud', competencyKey: 'mud_and_fluids', topicLabel: 'Mud', sampleQuestion: 'شلون اخترت أو عدّلت وزن الطين؟' },
                { stepKey: 'ops', competencyKey: 'drilling_operations', topicLabel: 'Operations', sampleQuestion: 'شنو المشكلة التشغيلية اللي واجهتك؟' },
                { stepKey: 'control', competencyKey: 'well_control', topicLabel: 'Well control', sampleQuestion: 'كيف تتأكد من جاهزية well control؟' },
                { stepKey: 'hse', competencyKey: 'hse_rig_safety', topicLabel: 'HSE', sampleQuestion: 'شنو إجراء السلامة اللي تأكدت منه؟' },
                { stepKey: 'result', topicLabel: 'Result', sampleQuestion: 'شنو النتيجة أو الدرس المستفاد؟' },
            ],
        },
    ],
};

export const CIVIL_ENGINEER: DomainPack = {
    packKey: 'civil_engineer',
    packVersion: WAVE_1B_PACK_VERSION,
    roleKey: 'civil_engineer',
    domain: 'engineering',
    specialization: 'Civil Engineering',
    roleAliases: [
        'civil engineer', 'civil engineering', 'structural civil',
        'مهندس مدني', 'هندسة مدنية',
    ],
    excludeKeywords: [
        'survey engineer', 'quantity surveyor', 'site engineer only',
        'petroleum', 'drilling', 'reservoir', 'recruiter',
    ],
    matchKeywords: [
        'civil', 'structural', 'concrete', 'rebar', 'earthworks', 'roads',
        'autocad', 'civil 3d', 'etabs', 'sap2000', 'boq', 'specifications',
        'مدني', 'خرسانة', 'حديد تسليح', 'طرق', 'أساسات',
    ],
    terminology: [
        'AutoCAD', 'Civil 3D', 'ETABS', 'SAP2000', 'rebar detailing',
        'concrete mix', 'soil investigation', 'bearing capacity', 'BOQ',
        'shop drawings', 'as-built', 'RFI', 'method statement', 'QA/QC',
        'earthworks', 'pavement design', 'retaining wall', 'formwork',
    ],
    domainGuidance: [
        'Domain: Civil Engineering — design, drawings, quantities, specs, QA/QC.',
        'Distinguish design-office civil from pure site supervision (site engineer pack).',
        'Probe real projects: scope, calculations, drawings reviewed, approval workflow.',
        'Weak answers: generic "I know AutoCAD" without project context.',
    ].join(' '),
    competencies: [
        {
            competencyKey: 'design_and_analysis',
            title: 'Design & Analysis',
            priority: 'critical',
            questionObjective: 'قياس القدرة على تحليل وتصميم عناصر إنشائية أو طرق.',
            expectedEvidence: ['حسابات', 'برنامج', 'معايير', 'افتراضات'],
            redFlags: ['لا حسابات', 'تصميم بلا معايير'],
            scoreRubric: rubricFor('drilling_program_design'),
            followUpRules: ['اسأل عن المعيار أو الافتراض الحاسم.'],
        },
        {
            competencyKey: 'drawings_and_documentation',
            title: 'Drawings & Technical Documentation',
            priority: 'critical',
            questionObjective: 'قياس مراجعة وإعداد المخططات وكميات الأعمال.',
            expectedEvidence: ['shop drawings', 'BOQ', 'تنسيق', 'اعتماد'],
            redFlags: ['أخطاء تنسيق', 'لا مراجعة'],
            scoreRubric: rubricFor('drawings_and_documentation'),
            followUpRules: ['اسأل عن خطأ اكتشفته بالمخططات.'],
        },
        {
            competencyKey: 'specifications_qa',
            title: 'Specifications & QA/QC',
            priority: 'high',
            questionObjective: 'قياس تطبيق المواصفات وضبط الجودة.',
            expectedEvidence: ['فحص', 'عدم مطابقة', 'إجراء تصحيحي'],
            redFlags: ['يتجاهل المواصفات'],
            scoreRubric: rubricFor('specifications_qa'),
            followUpRules: ['اطلب مثال NCR أو عدم مطابقة.'],
        },
        {
            competencyKey: 'site_coordination',
            title: 'Site & Stakeholder Coordination',
            priority: 'high',
            questionObjective: 'قياس التنسيق مع الموقع والمقاولين والاستشاريين.',
            expectedEvidence: ['RFI', 'اجتماعات', 'حل تعارض'],
            redFlags: ['لا تنسيق'],
            scoreRubric: rubricFor('site_coordination'),
            followUpRules: ['اسأل عن تعارض مخططات وكيف حُل.'],
        },
        {
            competencyKey: 'safety_and_risk',
            title: 'Safety & Construction Risk',
            priority: 'high',
            questionObjective: 'قياس إدراك مخاطر التنفيذ والسلامة.',
            expectedEvidence: ['تقييم مخاطر', 'إجراء وقائي', 'تصعيد'],
            redFlags: ['يتجاهل السلامة'],
            scoreRubric: rubricFor('safety_and_risk'),
            followUpRules: ['اسأل عن خطر لاحظته مبكراً.'],
        },
        {
            competencyKey: 'project_delivery',
            title: 'Project Delivery & Schedule Awareness',
            priority: 'medium',
            questionObjective: 'قياس الوعي بالجدول والتكلفة أثناء التصميم/المراجعة.',
            expectedEvidence: ['أولويات', 'تغيير نطاق', 'تأثير زمني'],
            redFlags: ['لا وعي بالتسليم'],
            scoreRubric: rubricFor('project_delivery'),
            followUpRules: ['اسأل كيف أثرت مراجعتك على الجدول.'],
        },
    ],
    suggestedAnchorQuestions: [
        'اذكرلي مشروع مدني اشتغلت عليه — شنو نوعه وشنو مسؤولياتك؟',
        'شلون تتأكد إن التصاميم أو الكميات مطابقة للمواصفات قبل التنفيذ؟',
        'اذكرلي مشكلة جودة أو سلامة بالموقع واجهتها كمهندس مدني — شنو سويت؟',
    ],
    supportedExperienceTracks: [
        {
            trackKey: 'academic_only',
            detectSignals: ['جامعة', 'تخرج', 'مشروع تخرج', 'thesis'],
            acceptableEvidence: ['تصميم أكاديمي', 'حسابات'],
            questionDifficulty: 1,
            openingAnchors: ['اذكرلي مشروع تخرج مدني — شنو صممت؟'],
            followUpHints: ['لا تفترض موقع كبير'],
        },
        {
            trackKey: 'trainee',
            detectSignals: ['تدريب', 'متدرب', 'internship'],
            acceptableEvidence: ['مهام محددة', 'مخططات'],
            questionDifficulty: 1,
            openingAnchors: ['شنو تعلمت بفترة التدريب بالمكتب أو الموقع؟'],
            followUpHints: ['إشراف'],
        },
        {
            trackKey: 'entry_level',
            detectSignals: ['خريج', 'حديث تخرج', 'أول وظيفة'],
            acceptableEvidence: ['أول مشروع', 'تعلم'],
            questionDifficulty: 1,
            openingAnchors: ['اذكرلي أول مهمة مدنية بعد التخرج.'],
            followUpHints: ['خطوات'],
        },
        {
            trackKey: 'experienced',
            detectSignals: ['مشروع', 'موقع', 'اشتغلت', 'autocad', 'etabs', 'concrete'],
            acceptableEvidence: ['مشروع كامل', 'مراجعة', 'نتيجة'],
            questionDifficulty: 3,
            openingAnchors: [
                'اذكرلي مشروع مدني كبير — شنو دورك بالتصميم أو المراجعة؟',
                'شلون تعاملت مع تعارض بالمخططات أو الكميات؟',
            ],
            followUpHints: ['تفاصيل تقنية'],
        },
        {
            trackKey: 'senior',
            detectSignals: ['senior', 'lead', 'manager', 'رئيس مهندسين'],
            acceptableEvidence: ['اعتماد', 'قيادة فريق', 'قرار تقني'],
            questionDifficulty: 3,
            openingAnchors: ['اذكرلي قرار تقني مهم قدته على مشروع مدني.'],
            followUpHints: ['تأثير'],
        },
        {
            trackKey: 'career_switcher',
            detectSignals: ['غيرت مجال', 'انتقلت', 'career change'],
            acceptableEvidence: ['تعلم مدني'],
            questionDifficulty: 2,
            openingAnchors: ['ليش انتقلت للهندسة المدنية؟'],
            followUpHints: ['مهارات منقولة'],
        },
    ],
    interviewPaths: [
        {
            pathKey: 'civil_design_review',
            steps: [
                { stepKey: 'project', topicLabel: 'Project', sampleQuestion: 'شنو نوع المشروع وحجمه؟' },
                { stepKey: 'role', competencyKey: 'design_and_analysis', topicLabel: 'Role', sampleQuestion: 'شنو مسؤوليتك بالتصميم أو التحليل؟' },
                { stepKey: 'drawings', competencyKey: 'drawings_and_documentation', topicLabel: 'Drawings', sampleQuestion: 'شنو راجعت بالمخططات أو الكميات؟' },
                { stepKey: 'quality', competencyKey: 'specifications_qa', topicLabel: 'Quality', sampleQuestion: 'اذكرلي مشكلة مواصفات أو جودة — شنو سويت؟' },
                { stepKey: 'coordination', competencyKey: 'site_coordination', topicLabel: 'Coordination', sampleQuestion: 'شلون نسّقت مع الموقع أو المقاول؟' },
                { stepKey: 'safety', competencyKey: 'safety_and_risk', topicLabel: 'Safety', sampleQuestion: 'شنو مخاطر لاحظتها مبكراً؟' },
                { stepKey: 'outcome', topicLabel: 'Outcome', sampleQuestion: 'شنو النتيجة؟' },
            ],
        },
    ],
};

export const SITE_ENGINEER: DomainPack = {
    packKey: 'site_engineer',
    packVersion: WAVE_1B_PACK_VERSION,
    roleKey: 'site_engineer',
    domain: 'engineering',
    specialization: 'Site Engineering',
    roleAliases: [
        'site engineer', 'site engineering', 'construction site engineer',
        'مهندس موقع', 'مهندس ميدان', 'إشراف موقع',
    ],
    excludeKeywords: [
        'reservoir', 'drilling', 'petroleum', 'survey engineer', 'recruiter',
        'software', 'backend developer',
    ],
    matchKeywords: [
        'site engineer', 'construction site', 'contractor', 'rfi', 'inspection',
        'daily report', 'method statement', 'progress', 'qa/qc', 'hse site',
        'موقع', 'مقاول', 'إشراف', 'تفتيش', 'محضر',
    ],
    terminology: [
        'RFI', 'method statement', 'ITP', 'inspection test plan', 'daily report',
        'work permit', 'HSE', 'NCR', 'punch list', 'as-built', 'variation order',
        'lookahead', 'manpower histogram', 'concrete pour', 'rebar inspection',
        'site logistics', 'coordination meeting', 'BOQ progress',
    ],
    domainGuidance: [
        'Domain: Site Engineering — daily site supervision, contractors, inspections, progress.',
        'Not design-office civil: focus execution, coordination, safety, documentation on site.',
        'Probe RFIs, inspections, conflicts between drawings and field reality.',
        'Weak answers: vague "I supervised" without examples or documents.',
    ].join(' '),
    competencies: [
        {
            competencyKey: 'daily_site_management',
            title: 'Daily Site Management',
            priority: 'critical',
            questionObjective: 'قياس إدارة الأعمال اليومية والتقدم والموارد.',
            expectedEvidence: ['تقارير يومية', 'تنسيق عمال', 'أولويات'],
            redFlags: ['لا روتين يومي'],
            scoreRubric: rubricFor('design_and_analysis'),
            followUpRules: ['اسأل شنو تفحص أول شي بالموقع.'],
        },
        {
            competencyKey: 'contractor_coordination',
            title: 'Contractor & Consultant Coordination',
            priority: 'critical',
            questionObjective: 'قياس التعامل مع المقاولين والاستشاريين.',
            expectedEvidence: ['اجتماعات', 'تعليمات', 'متابعة', 'تصعيد'],
            redFlags: ['صراع بلا حل'],
            scoreRubric: rubricFor('contractor_coordination'),
            followUpRules: ['اسأل عن تعارض مع مقاول.'],
        },
        {
            competencyKey: 'quality_inspections',
            title: 'Quality Inspections & ITP',
            priority: 'high',
            questionObjective: 'قياس تنفيذ خطط الفحص وعدم المطابقة.',
            expectedEvidence: ['ITP', 'فحص', 'NCR', 'إغلاق'],
            redFlags: ['يتجاوز الفحص'],
            scoreRubric: rubricFor('quality_inspections'),
            followUpRules: ['اطلب مثال فحص حرج.'],
        },
        {
            competencyKey: 'safety_site',
            title: 'Site Safety & Permits',
            priority: 'high',
            questionObjective: 'قياس السلامة والتصاريح الميدانية.',
            expectedEvidence: ['PTW', 'Toolbox talk', 'إيقاف عمل'],
            redFlags: ['يتجاهل السلامة'],
            scoreRubric: rubricFor('safety_site'),
            followUpRules: ['اسأل عن موقف أوقفت فيه عمل غير آمن.'],
        },
        {
            competencyKey: 'documentation_rfi',
            title: 'Documentation & RFIs',
            priority: 'high',
            questionObjective: 'قياس إدارة RFIs والمحاضر والتغييرات.',
            expectedEvidence: ['RFI', 'محضر', 'تتبع'],
            redFlags: ['قرارات شفهية بلا توثيق'],
            scoreRubric: rubricFor('documentation_rfi'),
            followUpRules: ['اسأل عن RFI أثر على الجدول.'],
        },
        {
            competencyKey: 'schedule_problem_solving',
            title: 'Schedule & Problem Solving',
            priority: 'medium',
            questionObjective: 'قياس التعامل مع التأخير ومشاكل الموقع.',
            expectedEvidence: ['سبب تأخير', 'خطة معالجة', 'تنسيق'],
            redFlags: ['لا خطة'],
            scoreRubric: rubricFor('schedule_problem_solving'),
            followUpRules: ['اسأل عن تأخير وكيف عالجته.'],
        },
    ],
    suggestedAnchorQuestions: [
        'اذكرلي موقع بناء أو مشروع اشرفت عليه — شنو كان حجم العمل وشنو دورك اليومي؟',
        'شلون تنسّق مع المقاولين والاستشاريين لما يصير تعارض بالمخططات؟',
        'اذكرلي موقف تأخّر فيه المشروع بسبب مشكلة ميدانية — شنو خطواتك؟',
    ],
    supportedExperienceTracks: [
        {
            trackKey: 'academic_only',
            detectSignals: ['جامعة', 'تخرج', 'زيارة موقع', 'مشروع تخرج'],
            acceptableEvidence: ['زيارات', 'تقارير أكاديمية'],
            questionDifficulty: 1,
            openingAnchors: ['اذكرلي تجربة موقع بالجامعة — شنو شفت؟'],
            followUpHints: ['لا تفترض إشراف كامل'],
        },
        {
            trackKey: 'trainee',
            detectSignals: ['تدريب', 'متدرب', 'internship'],
            acceptableEvidence: ['مهام محددة', 'تقارير'],
            questionDifficulty: 1,
            openingAnchors: ['شنو مسؤولياتك اليومية وأنت متدرب موقع؟'],
            followUpHints: ['إشراف'],
        },
        {
            trackKey: 'entry_level',
            detectSignals: ['خريج', 'حديث تخرج', 'أول وظيفة'],
            acceptableEvidence: ['أول موقع'],
            questionDifficulty: 1,
            openingAnchors: ['اذكرلي أول موقع بعد التخرج — شنو تعلمت؟'],
            followUpHints: ['خطوات'],
        },
        {
            trackKey: 'experienced',
            detectSignals: ['موقع', 'مقاول', 'rfi', 'inspection', 'اشتغلت', 'site'],
            acceptableEvidence: ['مشكلة حُلت', 'تفتيش', 'تقرير'],
            questionDifficulty: 3,
            openingAnchors: [
                'اذكرلي موقع صعب — شنو أكبر تحدي يومي واجهته؟',
                'شلون أغلقت NCR أو مشكلة جودة ميدانية؟',
            ],
            followUpHints: ['تفاصيل'],
        },
        {
            trackKey: 'senior',
            detectSignals: ['senior', 'lead', 'resident', 'مشرف', 'manager'],
            acceptableEvidence: ['قيادة', 'قرار', 'تأثير جدول'],
            questionDifficulty: 3,
            openingAnchors: ['اذكرلي قرار ميداني مهم أثّر على سير المشروع.'],
            followUpHints: ['تأثير'],
        },
        {
            trackKey: 'career_switcher',
            detectSignals: ['غيرت مجال', 'انتقلت', 'career change'],
            acceptableEvidence: ['تعلم موقع'],
            questionDifficulty: 2,
            openingAnchors: ['ليش انتقلت لإشراف المواقع؟'],
            followUpHints: ['مهارات منقولة'],
        },
    ],
    interviewPaths: [
        {
            pathKey: 'site_daily_flow',
            steps: [
                { stepKey: 'site', topicLabel: 'Site', sampleQuestion: 'شنو نوع المشروع ومرحلته؟' },
                { stepKey: 'routine', competencyKey: 'daily_site_management', topicLabel: 'Routine', sampleQuestion: 'شلون يبدأ يومك بالموقع؟' },
                { stepKey: 'hse', competencyKey: 'safety_site', topicLabel: 'HSE', sampleQuestion: 'شلون تتأكد من التصاريح وHSE قبل الأعمال؟' },
                { stepKey: 'issue', competencyKey: 'schedule_problem_solving', topicLabel: 'Issue', sampleQuestion: 'اذكرلي مشكلة ميدانية — شنو السبب؟' },
                { stepKey: 'coordination', competencyKey: 'contractor_coordination', topicLabel: 'Coordination', sampleQuestion: 'شلون نسّقت الحل مع المقاول؟' },
                { stepKey: 'quality', competencyKey: 'quality_inspections', topicLabel: 'Quality', sampleQuestion: 'شلون تأكدت من جودة التنفيذ؟' },
                { stepKey: 'close', topicLabel: 'Close', sampleQuestion: 'شنو النتيجة أو الدرس؟' },
            ],
        },
    ],
};

export const PROCESS_ENGINEER: DomainPack = {
    packKey: 'process_engineer',
    packVersion: WAVE_1B_PACK_VERSION,
    roleKey: 'process_engineer',
    domain: 'engineering',
    specialization: 'Process Engineering',
    roleAliases: [
        'process engineer', 'process engineering', 'chemical process engineer',
        'مهندس عمليات', 'هندسة عمليات', 'مهندس عمليات كيميائية',
    ],
    excludeKeywords: [
        'software process', 'agile process', 'hr process', 'recruiter',
        'lean manufacturing only', 'assembly line operator', 'cnc',
        'reservoir engineer', 'drilling engineer',
    ],
    matchKeywords: [
        'process engineer', 'pfd', 'pid', 'mass balance', 'energy balance',
        'hazop', 'relief valve', 'distillation', 'heat exchanger', 'refinery',
        'chemical plant', 'throughput', 'debottleneck', 'عمليات', 'مخطط عمليات',
    ],
    terminology: [
        'PFD', 'P&ID', 'mass balance', 'energy balance', 'HAZOP', 'LOPA',
        'relief sizing', 'heat exchanger', 'distillation column', 'separator',
        'debottlenecking', 'operating envelope', 'DCS', 'start-up shutdown',
        'catalyst', 'utility consumption', 'process safety', 'HSE',
    ],
    domainGuidance: [
        'Domain: Process Engineering — flowsheets, balances, safety, optimization (plant/refinery/chemical).',
        'Exclude manufacturing lean/OEE-only roles unless process plant context is clear.',
        'Probe PFD/P&ID changes, HAZOP findings, measurable throughput/utility improvements.',
        'Weak answers: buzzwords without units, balances, or outcomes.',
    ].join(' '),
    competencies: [
        {
            competencyKey: 'process_design',
            title: 'Process Design & Flowsheets',
            priority: 'critical',
            questionObjective: 'قياس فهم تصميم العملية ومخططات PFD/P&ID.',
            expectedEvidence: ['PFD/P&ID', 'توازن', 'اختيار معدات'],
            redFlags: ['لا مخططات', 'خلط معدات بلا سبب'],
            scoreRubric: rubricFor('daily_site_management'),
            followUpRules: ['اسأل لماذا اختيرت وحدة معينة.'],
        },
        {
            competencyKey: 'mass_energy_balance',
            title: 'Mass & Energy Balances',
            priority: 'critical',
            questionObjective: 'قياس إجراء توازن الكتلة/الطاقة واتخاذ قرار.',
            expectedEvidence: ['مدخلات/مخرجات', 'وحدات', 'تحقق'],
            redFlags: ['لا أرقام', 'توازن غير منطقي'],
            scoreRubric: rubricFor('mass_energy_balance'),
            followUpRules: ['اطلب رقم أو نسبة تحسن.'],
        },
        {
            competencyKey: 'process_safety',
            title: 'Process Safety & HAZOP',
            priority: 'high',
            questionObjective: 'قياس المشاركة بسلامة العمليات وتحليل المخاطر.',
            expectedEvidence: ['HAZOP', 'relief', 'إجراء', 'توصية'],
            redFlags: ['يتجاهل السلامة'],
            scoreRubric: rubricFor('process_safety'),
            followUpRules: ['اسأل عن توصية HAZOP نُفذت.'],
        },
        {
            competencyKey: 'troubleshooting',
            title: 'Operations Troubleshooting',
            priority: 'high',
            questionObjective: 'قياس تشخيص مشاكل تشغيل (جودة، throughput، utilities).',
            expectedEvidence: ['أعراض', 'سبب جذري', 'إجراء'],
            redFlags: ['تخمين بلا بيانات'],
            scoreRubric: rubricFor('troubleshooting'),
            followUpRules: ['اسأل عن بيانات DCS أو عينات استخدمتها.'],
        },
        {
            competencyKey: 'optimization',
            title: 'Debottlenecking & Optimization',
            priority: 'high',
            questionObjective: 'قياس تحسين العملية أو تقليل استهلاك.',
            expectedEvidence: ['قبل/بعد', 'KPI', 'تكلفة/طاقة'],
            redFlags: ['لا قياس'],
            scoreRubric: rubricFor('optimization'),
            followUpRules: ['اطلب نسبة تحسن.'],
        },
        {
            competencyKey: 'cross_functional',
            title: 'Cross-functional Coordination',
            priority: 'medium',
            questionObjective: 'قياس التنسيق مع العمليات والصيانة والسلامة.',
            expectedEvidence: ['اجتماعات', 'تغييرات', 'تشغيل'],
            redFlags: ['عزلة عن العمليات'],
            scoreRubric: rubricFor('cross_functional'),
            followUpRules: ['اسأل كيف نُفذ التغيير على الأرض.'],
        },
    ],
    suggestedAnchorQuestions: [
        'اذكرلي عملية أو وحدة هندسة عمليات صممتها أو حسّنتها — شنو الهدف وشنو النتيجة؟',
        'شلون تراجع توازن الكتلة أو الطاقة قبل تعديل العملية؟',
        'اذكرلي حالة اكتشفت فيها مخاطر عملية — شنو الإجراء اللي اتخذته؟',
    ],
    supportedExperienceTracks: [
        {
            trackKey: 'academic_only',
            detectSignals: ['جامعة', 'تخرج', 'مشروع تخرج', 'thesis', 'محاكاة'],
            acceptableEvidence: ['تصميم أكاديمي', 'توازن نظري'],
            questionDifficulty: 1,
            openingAnchors: ['اذكرلي مشروع عمليات بالجامعة — شنو صممت؟'],
            followUpHints: ['لا تفترض تشغيل مصنع'],
        },
        {
            trackKey: 'trainee',
            detectSignals: ['تدريب', 'متدرب', 'internship', 'plant visit'],
            acceptableEvidence: ['ملاحظات', 'مهام'],
            questionDifficulty: 1,
            openingAnchors: ['شنو تعلمت بزيارة مصنع أو تدريب عمليات؟'],
            followUpHints: ['إشراف'],
        },
        {
            trackKey: 'entry_level',
            detectSignals: ['خريج', 'حديث تخرج', 'أول وظيفة'],
            acceptableEvidence: ['أول مهمة'],
            questionDifficulty: 1,
            openingAnchors: ['اذكرلي أول مهمة عمليات بعد التخرج.'],
            followUpHints: ['خطوات'],
        },
        {
            trackKey: 'experienced',
            detectSignals: ['مصنع', 'وحدة', 'p&id', 'hazop', 'plant', 'اشتغلت', 'refinery'],
            acceptableEvidence: ['تحسين قابل للقياس', 'سلامة'],
            questionDifficulty: 3,
            openingAnchors: [
                'اذكرلي وحدة عمليات حسّنتها — شنو المشكلة والحل؟',
                'شلون شاركت بـ HAZOP أو مراجعة أمان؟',
            ],
            followUpHints: ['أرقام'],
        },
        {
            trackKey: 'senior',
            detectSignals: ['senior', 'lead', 'manager', 'head'],
            acceptableEvidence: ['قرار استثمار', 'فريق', 'تأثير'],
            questionDifficulty: 3,
            openingAnchors: ['اذكرلي قرار عمليات مهم أثّر على الإنتاج أو السلامة.'],
            followUpHints: ['trade-offs'],
        },
        {
            trackKey: 'career_switcher',
            detectSignals: ['غيرت مجال', 'انتقلت', 'career change'],
            acceptableEvidence: ['تعلم عمليات'],
            questionDifficulty: 2,
            openingAnchors: ['ليش انتقلت لهندسة العمليات؟'],
            followUpHints: ['مهارات منقولة'],
        },
    ],
    interviewPaths: [
        {
            pathKey: 'process_improvement',
            steps: [
                { stepKey: 'unit', topicLabel: 'Unit', sampleQuestion: 'شنو الوحدة أو العملية؟' },
                { stepKey: 'design', competencyKey: 'process_design', topicLabel: 'Design', sampleQuestion: 'شلون راجعت PFD/P&ID قبل التعديل؟' },
                { stepKey: 'problem', competencyKey: 'troubleshooting', topicLabel: 'Problem', sampleQuestion: 'شنو المشكلة أو الهدف؟' },
                { stepKey: 'analysis', competencyKey: 'mass_energy_balance', topicLabel: 'Analysis', sampleQuestion: 'شلون حللت بالتوازن أو البيانات؟' },
                { stepKey: 'safety', competencyKey: 'process_safety', topicLabel: 'Safety', sampleQuestion: 'شنو اعتبار السلامة بالقرار؟' },
                { stepKey: 'coordination', competencyKey: 'cross_functional', topicLabel: 'Coordination', sampleQuestion: 'شلون نسّقت مع العمليات والصيانة؟' },
                { stepKey: 'result', competencyKey: 'optimization', topicLabel: 'Result', sampleQuestion: 'شنو النتيجة القابلة للقياس؟' },
            ],
        },
    ],
};

function preferredTracksForPath(path: InterviewPath): ExperienceTrackKey[] {
    if (path.pathKey.includes('academic')) return ACADEMIC_TRACKS;
    if (
        path.pathKey.includes('experienced')
        || path.pathKey.includes('field')
        || path.pathKey.includes('operations')
        || path.pathKey.includes('design')
        || path.pathKey.includes('daily')
        || path.pathKey.includes('improvement')
    ) {
        return FIELD_TRACKS;
    }
    return [...ACADEMIC_TRACKS, ...FIELD_TRACKS];
}

function enrichWave1bPack(pack: DomainPack): DomainPack {
    return {
        ...pack,
        packVersion: WAVE_3_ENRICHED_VERSION,
        competencies: pack.competencies.map((c) => ({
            ...c,
            scoreRubric: rubricFor(c.competencyKey),
        })),
        interviewPaths: (pack.interviewPaths ?? []).map((path) =>
            enrichedPath(path.pathKey, preferredTracksForPath(path), path.steps)
        ),
    };
}

export const WAVE_1B_PACKS: DomainPack[] = [
    RESERVOIR_ENGINEER,
    DRILLING_ENGINEER,
    CIVIL_ENGINEER,
    SITE_ENGINEER,
    PROCESS_ENGINEER,
].map(enrichWave1bPack);
