// Font options for font dropdown
export const fontOptions = [
    { font: 'None', fontFamily: "'Inter', sans-serif", fontUrl: '', label: 'None' },
    // Arabic Fonts
    { font: 'Reem Kufi', fontFamily: "'Reem Kufi', sans-serif", fontUrl: 'https://fonts.googleapis.com/css2?family=Reem+Kufi:wght@400;500;600;700&display=swap', label: 'كوفي' },
    { font: 'GE SS', fontFamily: "'GE SS Two', 'GE SS Unique', 'GESS', Arial, sans-serif", fontUrl: '', label: 'جي إي إس إس' },
    { font: 'Mirza', fontFamily: "'Mirza', serif", fontUrl: 'https://fonts.googleapis.com/css2?family=Mirza:wght@400;500;600;700&display=swap', label: 'ثلث' },
    { font: 'Katibeh', fontFamily: "'Katibeh', serif", fontUrl: 'https://fonts.googleapis.com/css2?family=Katibeh:wght@400&display=swap', label: 'ثلث أنيق' },
    { font: 'Aref Ruqaa', fontFamily: "'Aref Ruqaa', serif", fontUrl: 'https://fonts.googleapis.com/css2?family=Aref+Ruqaa:wght@400;700&display=swap', label: 'رقعة' },
    { font: 'Lalezar', fontFamily: "'Lalezar', cursive", fontUrl: 'https://fonts.googleapis.com/css2?family=Lalezar&display=swap', label: 'ديواني' },
    { font: 'Aladin', fontFamily: "'Aladin', cursive", fontUrl: 'https://fonts.googleapis.com/css2?family=Aladin&display=swap', label: 'ديواني فني' },
    { font: 'Rakkas', fontFamily: "'Rakkas', serif", fontUrl: 'https://fonts.googleapis.com/css2?family=Rakkas:wght@400&display=swap', label: 'كوفي كلاسيكي' },
    { font: 'Lateef', fontFamily: "'Lateef', serif", fontUrl: 'https://fonts.googleapis.com/css2?family=Lateef:wght@400;600;700&display=swap', label: 'نسخ لطيف' },
    { font: 'Scheherazade New', fontFamily: "'Scheherazade New', serif", fontUrl: 'https://fonts.googleapis.com/css2?family=Scheherazade+New:wght@400;500;600;700&display=swap', label: 'نسخ شهرزاد' },
    { font: 'Amiri', fontFamily: "'Amiri', serif", fontUrl: 'https://fonts.googleapis.com/css2?family=Amiri:wght@400;700&display=swap', label: 'نسخ أميري' },
    { font: 'Markazi Text', fontFamily: "'Markazi Text', serif", fontUrl: 'https://fonts.googleapis.com/css2?family=Markazi+Text:wght@400;500;600;700&display=swap', label: 'نسخ مركزي' },
    { font: 'Harmattan', fontFamily: "'Harmattan', sans-serif", fontUrl: 'https://fonts.googleapis.com/css2?family=Harmattan:wght@400;500;600;700&display=swap', label: 'نسخ حرمطان' },
    { font: 'Mada', fontFamily: "'Mada', sans-serif", fontUrl: 'https://fonts.googleapis.com/css2?family=Mada:wght@300;400;500;600;700;800;900&display=swap', label: 'نسخ معدا' },
    { font: 'Cairo', fontFamily: "'Cairo', sans-serif", fontUrl: 'https://fonts.googleapis.com/css2?family=Cairo:wght@300;400;500;600;700;800&display=swap', label: 'نسخ القاهرة' },
    { font: 'Noto Sans Arabic', fontFamily: "'Noto Sans Arabic', sans-serif", fontUrl: 'https://fonts.googleapis.com/css2?family=Noto+Sans+Arabic:wght@300;400;500;600;700;800&display=swap', label: 'نسخ نوتو' },
    { font: 'Tajawal', fontFamily: "'Tajawal', sans-serif", fontUrl: 'https://fonts.googleapis.com/css2?family=Tajawal:wght@300;400;500;700;800;900&display=swap', label: 'نسخ تجوال' },
    { font: 'Almarai', fontFamily: "'Almarai', sans-serif", fontUrl: 'https://fonts.googleapis.com/css2?family=Almarai:wght@300;400;700;800&display=swap', label: 'نسخ المراعي' },
    { font: 'Changa', fontFamily: "'Changa', sans-serif", fontUrl: 'https://fonts.googleapis.com/css2?family=Changa:wght@300;400;500;600;700;800&display=swap', label: 'نسخ شانجا' },
    { font: 'El Messiri', fontFamily: "'El Messiri', sans-serif", fontUrl: 'https://fonts.googleapis.com/css2?family=El+Messiri:wght@400;500;600;700&display=swap', label: 'نسخ المسيري' },
    { font: 'IBM Plex Sans Arabic', fontFamily: "'IBM Plex Sans Arabic', sans-serif", fontUrl: 'https://fonts.googleapis.com/css2?family=IBM+Plex+Sans+Arabic:wght@100;200;300;400;500;600;700&display=swap', label: 'نسخ آي بي إم' },
    { font: 'Dubai Font', fontFamily: "'Dubai', 'Dubai-Regular', Arial, sans-serif", fontUrl: '', label: 'خط دبي' },
    { font: 'Madani', fontFamily: "'Madani', 'Al Madani', Arial, sans-serif", fontUrl: '', label: 'مدني' },
    { font: 'Vazirmatn', fontFamily: "'Vazirmatn', sans-serif", fontUrl: 'https://fonts.googleapis.com/css2?family=Vazirmatn:wght@100;200;300;400;500;600;700;800;900&display=swap', label: 'نسخ وزيرمتن' },
    { font: 'Rubik', fontFamily: "'Rubik', sans-serif", fontUrl: 'https://fonts.googleapis.com/css2?family=Rubik:wght@300;400;500;600;700;800;900&display=swap', label: 'نسخ روبيك' },
    // English & International Fonts
    { font: 'Inter', fontFamily: "'Inter', sans-serif", fontUrl: 'https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&display=swap', label: 'Inter' },
    { font: 'Poppins', fontFamily: "'Poppins', sans-serif", fontUrl: 'https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700;800&display=swap', label: 'Poppins' },
    { font: 'Roboto', fontFamily: "'Roboto', sans-serif", fontUrl: 'https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&display=swap', label: 'Roboto' },
    { font: 'Open Sans', fontFamily: "'Open Sans', sans-serif", fontUrl: 'https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400;500;600;700;800&display=swap', label: 'Open Sans' },
    { font: 'Lato', fontFamily: "'Lato', sans-serif", fontUrl: 'https://fonts.googleapis.com/css2?family=Lato:wght@300;400;700;900&display=swap', label: 'Lato' },
    { font: 'Montserrat', fontFamily: "'Montserrat', sans-serif", fontUrl: 'https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500;600;700;800&display=swap', label: 'Montserrat' },
    { font: 'Raleway', fontFamily: "'Raleway', sans-serif", fontUrl: 'https://fonts.googleapis.com/css2?family=Raleway:wght@300;400;500;600;700;800&display=swap', label: 'Raleway' },
    { font: 'Nunito', fontFamily: "'Nunito', sans-serif", fontUrl: 'https://fonts.googleapis.com/css2?family=Nunito:wght@300;400;500;600;700;800&display=swap', label: 'Nunito' },
    { font: 'Playfair Display', fontFamily: "'Playfair Display', serif", fontUrl: 'https://fonts.googleapis.com/css2?family=Playfair+Display:wght@400;500;600;700;800&display=swap', label: 'Playfair Display' },
    { font: 'Merriweather', fontFamily: "'Merriweather', serif", fontUrl: 'https://fonts.googleapis.com/css2?family=Merriweather:wght@300;400;700;900&display=swap', label: 'Merriweather' },
    { font: 'Ubuntu', fontFamily: "'Ubuntu', sans-serif", fontUrl: 'https://fonts.googleapis.com/css2?family=Ubuntu:wght@300;400;500;700&display=swap', label: 'Ubuntu' },
    { font: 'Source Sans Pro', fontFamily: "'Source Sans Pro', sans-serif", fontUrl: 'https://fonts.googleapis.com/css2?family=Source+Sans+Pro:wght@300;400;600;700&display=swap', label: 'Source Sans Pro' },
    { font: 'Helvetica Neue', fontFamily: "'Helvetica Neue', Helvetica, Arial, sans-serif", fontUrl: '', label: 'Helvetica Neue' },
    { font: 'SF Pro', fontFamily: "-apple-system, 'SF Pro Display', 'SF Pro Text', system-ui, sans-serif", fontUrl: '', label: 'SF Pro' },
    { font: 'Work Sans', fontFamily: "'Work Sans', sans-serif", fontUrl: 'https://fonts.googleapis.com/css2?family=Work+Sans:wght@300;400;500;600;700&display=swap', label: 'Work Sans' },
    { font: 'DM Sans', fontFamily: "'DM Sans', sans-serif", fontUrl: 'https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;700&display=swap', label: 'DM Sans' },
    { font: 'Manrope', fontFamily: "'Manrope', sans-serif", fontUrl: 'https://fonts.googleapis.com/css2?family=Manrope:wght@300;400;500;600;700;800&display=swap', label: 'Manrope' },
    { font: 'Space Grotesk', fontFamily: "'Space Grotesk', sans-serif", fontUrl: 'https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@300;400;500;600;700&display=swap', label: 'Space Grotesk' },
    { font: 'Arial', fontFamily: 'Arial, sans-serif', fontUrl: '', label: 'Arial' },
    { font: 'Helvetica', fontFamily: 'Helvetica, Arial, sans-serif', fontUrl: '', label: 'Helvetica' },
    { font: 'Times New Roman', fontFamily: "'Times New Roman', Times, serif", fontUrl: '', label: 'Times New Roman' },
    { font: 'Georgia', fontFamily: 'Georgia, serif', fontUrl: '', label: 'Georgia' },
    { font: 'Verdana', fontFamily: 'Verdana, Geneva, sans-serif', fontUrl: '', label: 'Verdana' },
    { font: 'Tahoma', fontFamily: 'Tahoma, Geneva, sans-serif', fontUrl: '', label: 'Tahoma' },
    { font: 'Courier New', fontFamily: "'Courier New', Courier, monospace", fontUrl: '', label: 'Courier New' },
    { font: 'Comic Sans MS', fontFamily: "'Comic Sans MS', cursive", fontUrl: '', label: 'Comic Sans MS' },
    { font: 'Trebuchet MS', fontFamily: "'Trebuchet MS', sans-serif", fontUrl: '', label: 'Trebuchet MS' },
    { font: 'Impact', fontFamily: 'Impact, Charcoal, sans-serif', fontUrl: '', label: 'Impact' },
    { font: 'Lucida Console', fontFamily: "'Lucida Console', Monaco, monospace", fontUrl: '', label: 'Lucida Console' },
    { font: 'Palatino', fontFamily: "Palatino, 'Palatino Linotype', serif", fontUrl: '', label: 'Palatino' },
    { font: 'Garamond', fontFamily: 'Garamond, serif', fontUrl: '', label: 'Garamond' },
    { font: 'Book Antiqua', fontFamily: "'Book Antiqua', Palatino, serif", fontUrl: '', label: 'Book Antiqua' },
    { font: 'Arial Black', fontFamily: "'Arial Black', Gadget, sans-serif", fontUrl: '', label: 'Arial Black' },
    { font: 'Comic Sans', fontFamily: "'Comic Sans MS', cursive", fontUrl: '', label: 'Comic Sans' },
    { font: 'Lucida Sans Unicode', fontFamily: "'Lucida Sans Unicode', 'Lucida Grande', sans-serif", fontUrl: '', label: 'Lucida Sans Unicode' },
    { font: 'MS Sans Serif', fontFamily: "'MS Sans Serif', Geneva, sans-serif", fontUrl: '', label: 'MS Sans Serif' },
    { font: 'MS Serif', fontFamily: "'MS Serif', 'New York', serif", fontUrl: '', label: 'MS Serif' },
    { font: 'Baskerville', fontFamily: "Baskerville, 'Baskerville Old Face', serif", fontUrl: '', label: 'Baskerville' },
    { font: 'Calibri', fontFamily: 'Calibri, Candara, sans-serif', fontUrl: '', label: 'Calibri' },
    { font: 'Cambria', fontFamily: 'Cambria, Georgia, serif', fontUrl: '', label: 'Cambria' },
    { font: 'Candara', fontFamily: 'Candara, Calibri, sans-serif', fontUrl: '', label: 'Candara' },
    { font: 'Century Gothic', fontFamily: "'Century Gothic', sans-serif", fontUrl: '', label: 'Century Gothic' },
    { font: 'Consolas', fontFamily: "Consolas, 'Courier New', monospace", fontUrl: '', label: 'Consolas' },
    { font: 'Copperplate', fontFamily: "Copperplate, 'Copperplate Gothic Light', fantasy", fontUrl: '', label: 'Copperplate' },
    { font: 'Franklin Gothic Medium', fontFamily: "'Franklin Gothic Medium', 'Arial Narrow', sans-serif", fontUrl: '', label: 'Franklin Gothic Medium' },
    { font: 'Gill Sans', fontFamily: "'Gill Sans', 'Gill Sans MT', sans-serif", fontUrl: '', label: 'Gill Sans' },
    { font: 'Lucida Grande', fontFamily: "'Lucida Grande', 'Lucida Sans Unicode', sans-serif", fontUrl: '', label: 'Lucida Grande' },
    { font: 'Segoe UI', fontFamily: "'Segoe UI', Tahoma, sans-serif", fontUrl: '', label: 'Segoe UI' },
    { font: 'Bebas Neue', fontFamily: "'Bebas Neue', cursive", fontUrl: 'https://fonts.googleapis.com/css2?family=Bebas+Neue&display=swap', label: 'Bebas Neue' },
    { font: 'Oswald', fontFamily: "'Oswald', sans-serif", fontUrl: 'https://fonts.googleapis.com/css2?family=Oswald:wght@300;400;500;600;700&display=swap', label: 'Oswald' },
    { font: 'Lora', fontFamily: "'Lora', serif", fontUrl: 'https://fonts.googleapis.com/css2?family=Lora:wght@400;500;600;700&display=swap', label: 'Lora' },
    { font: 'PT Sans', fontFamily: "'PT Sans', sans-serif", fontUrl: 'https://fonts.googleapis.com/css2?family=PT+Sans:wght@400;700&display=swap', label: 'PT Sans' },
    { font: 'PT Serif', fontFamily: "'PT Serif', serif", fontUrl: 'https://fonts.googleapis.com/css2?family=PT+Serif:wght@400;700&display=swap', label: 'PT Serif' },
    { font: 'Dancing Script', fontFamily: "'Dancing Script', cursive", fontUrl: 'https://fonts.googleapis.com/css2?family=Dancing+Script:wght@400;500;600;700&display=swap', label: 'Dancing Script' },
    { font: 'Pacifico', fontFamily: "'Pacifico', cursive", fontUrl: 'https://fonts.googleapis.com/css2?family=Pacifico&display=swap', label: 'Pacifico' },
    { font: 'Lobster', fontFamily: "'Lobster', cursive", fontUrl: 'https://fonts.googleapis.com/css2?family=Lobster&display=swap', label: 'Lobster' },
    { font: 'Righteous', fontFamily: "'Righteous', cursive", fontUrl: 'https://fonts.googleapis.com/css2?family=Righteous&display=swap', label: 'Righteous' },
    { font: 'Anton', fontFamily: "'Anton', sans-serif", fontUrl: 'https://fonts.googleapis.com/css2?family=Anton&display=swap', label: 'Anton' },
    { font: 'Bangers', fontFamily: "'Bangers', cursive", fontUrl: 'https://fonts.googleapis.com/css2?family=Bangers&display=swap', label: 'Bangers' },
    { font: 'Fredoka One', fontFamily: "'Fredoka One', cursive", fontUrl: 'https://fonts.googleapis.com/css2?family=Fredoka+One&display=swap', label: 'Fredoka One' },
    { font: 'Quicksand', fontFamily: "'Quicksand', sans-serif", fontUrl: 'https://fonts.googleapis.com/css2?family=Quicksand:wght@300;400;500;600;700&display=swap', label: 'Quicksand' },
    { font: 'Fira Sans', fontFamily: "'Fira Sans', sans-serif", fontUrl: 'https://fonts.googleapis.com/css2?family=Fira+Sans:wght@300;400;500;600;700;800&display=swap', label: 'Fira Sans' },
    { font: 'Libre Baskerville', fontFamily: "'Libre Baskerville', serif", fontUrl: 'https://fonts.googleapis.com/css2?family=Libre+Baskerville:wght@400;700&display=swap', label: 'Libre Baskerville' },
    { font: 'Crimson Text', fontFamily: "'Crimson Text', serif", fontUrl: 'https://fonts.googleapis.com/css2?family=Crimson+Text:wght@400;600;700&display=swap', label: 'Crimson Text' },
    { font: 'Josefin Sans', fontFamily: "'Josefin Sans', sans-serif", fontUrl: 'https://fonts.googleapis.com/css2?family=Josefin+Sans:wght@300;400;500;600;700&display=swap', label: 'Josefin Sans' },
    { font: 'Kalam', fontFamily: "'Kalam', cursive", fontUrl: 'https://fonts.googleapis.com/css2?family=Kalam:wght@300;400;700&display=swap', label: 'Kalam' },
    { font: 'Permanent Marker', fontFamily: "'Permanent Marker', cursive", fontUrl: 'https://fonts.googleapis.com/css2?family=Permanent+Marker&display=swap', label: 'Permanent Marker' },
    { font: 'Shadows Into Light', fontFamily: "'Shadows Into Light', cursive", fontUrl: 'https://fonts.googleapis.com/css2?family=Shadows+Into+Light&display=swap', label: 'Shadows Into Light' },
    { font: 'Amatic SC', fontFamily: "'Amatic SC', cursive", fontUrl: 'https://fonts.googleapis.com/css2?family=Amatic+SC:wght@400;700&display=swap', label: 'Amatic SC' },
    { font: 'Bree Serif', fontFamily: "'Bree Serif', serif", fontUrl: 'https://fonts.googleapis.com/css2?family=Bree+Serif&display=swap', label: 'Bree Serif' },
    { font: 'Dosis', fontFamily: "'Dosis', sans-serif", fontUrl: 'https://fonts.googleapis.com/css2?family=Dosis:wght@300;400;500;600;700;800&display=swap', label: 'Dosis' },
    { font: 'Exo', fontFamily: "'Exo', sans-serif", fontUrl: 'https://fonts.googleapis.com/css2?family=Exo:wght@300;400;500;600;700;800&display=swap', label: 'Exo' },
    { font: 'Orbitron', fontFamily: "'Orbitron', sans-serif", fontUrl: 'https://fonts.googleapis.com/css2?family=Orbitron:wght@400;500;600;700;800;900&display=swap', label: 'Orbitron' },
    { font: 'Rajdhani', fontFamily: "'Rajdhani', sans-serif", fontUrl: 'https://fonts.googleapis.com/css2?family=Rajdhani:wght@300;400;500;600;700&display=swap', label: 'Rajdhani' },
    { font: 'Titillium Web', fontFamily: "'Titillium Web', sans-serif", fontUrl: 'https://fonts.googleapis.com/css2?family=Titillium+Web:wght@300;400;600;700&display=swap', label: 'Titillium Web' },
    { font: 'Yanone Kaffeesatz', fontFamily: "'Yanone Kaffeesatz', sans-serif", fontUrl: 'https://fonts.googleapis.com/css2?family=Yanone+Kaffeesatz:wght@300;400;500;600;700&display=swap', label: 'Yanone Kaffeesatz' }
];



