/**
 * Suggested key skills for the application form (same combobox UX as position / languages).
 * Users can still type skills not in this list.
 */
export const KEY_SKILL_SUGGESTIONS = [
    'Communication',
    'Verbal Communication',
    'Written Communication',
    'Active Listening',
    'Leadership',
    'Teamwork',
    'Collaboration',
    'Team Management',
    'People Management',
    'Problem Solving',
    'Critical Thinking',
    'Analytical Thinking',
    'Strategic Thinking',
    'Creative Thinking',
    'Decision Making',
    'Time Management',
    'Organization',
    'Planning',
    'Prioritization',
    'Scheduling',
    'Adaptability',
    'Flexibility',
    'Resilience',
    'Initiative',
    'Self-Motivation',
    'Accountability',
    'Ownership',
    'Reliability',
    'Professionalism',
    'Ethics',
    'Integrity',
    'Attention to Detail',
    'Accuracy',
    'Multitasking',
    'Work Under Pressure',
    'Fast Learner',
    'Continuous Learning',
    'Research',
    'Investigation',
    'Documentation',
    'Report Writing',
    'Presentation Skills',
    'Public Speaking',
    'Negotiation',
    'Persuasion',
    'Influencing',
    'Networking',
    'Relationship Building',
    'Conflict Resolution',
    'Mediation',
    'Coaching',
    'Mentoring',
    'Customer Service',
    'Customer Support',
    'Customer Success',
    'Complaint Handling',
    'Sales',
    'Business Development',
    'Account Management',
    'Client Management',
    'Project Management',
    'Project Coordination',
    'Risk Management',
    'Change Management',
    'Process Improvement',
    'Business Analysis',
    'Data Analysis',
    'Data Entry',
    'Data Visualization',
    'Quality Assurance',
    'Quality Control',
    'Compliance',
    'Auditing',
    'Procurement',
    'Inventory Management',
    'Supply Chain',
    'Logistics',
    'Budgeting',
    'Cost Control',
    'Financial Analysis',
    'Recruitment',
    'Talent Acquisition',
    'Interviewing',
    'Onboarding',
    'Performance Management',
    'Employee Relations',
    'Training',
    'Learning & Development',
    'Microsoft Office',
    'Excel',
    'Word',
    'PowerPoint',
    'Outlook',
    'Google Workspace',
    'Email Communication',
    'CRM',
    'ERP',
    'SQL',
    'HTML',
    'CSS',
    'JavaScript',
    'Python',
    'Git',
    'REST APIs',
    'Figma',
    'UI/UX Design',
    'SEO',
    'Digital Marketing',
    'Social Media Marketing',
    'Content Creation',
];
