/**
 * Suggested key skills for the application form (same combobox UX as position / languages).
 * Users can still type skills not in this list.
 */
export const KEY_SKILL_SUGGESTIONS = [
    'Agile / Scrum',
    'AWS',
    'Business Analysis',
    'C#',
    'Communication',
    'CSS',
    'Customer Service',
    'Cybersecurity',
    'Data Analysis',
    'Docker',
    'Excel',
    'Figma',
    'Git',
    'HTML',
    'Java',
    'JavaScript',
    'Kubernetes',
    'Leadership',
    'Machine Learning',
    'Microsoft Office',
    'Node.js',
    'PostgreSQL',
    'Power BI',
    'Problem Solving',
    'Project Management',
    'Python',
    'React',
    'REST APIs',
    'Sales',
    'SEO',
    'SQL',
    'Teamwork',
    'TypeScript',
    'UI/UX Design',
];
